version: "3"

volumes:
  mysql_volume: {}

services:

  db:
    image: mysql:5.7
    restart: always
    environment:
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'MYSQL_DATABASE=nextjs-shop'
      - 'MYSQL_USER=user'
      - 'MYSQL_PASSWORD=root'
    ports:
      - 3306:3306
    volumes:
      - mysql_volume:/var/lib/mysql

  graphql:
    ports:
      - 5000:5000
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/usr/src/server
      - /usr/src/server/node_modules
    environment:
      - PORT=5000
      - DATABASE_HOST=db
      - DATABASE_URL=mysql://user:root@host.docker.internal:3306/nextjs-shop
      - DATABASE_USER=user
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=nextjs-shop
      - DATABASE_PORT=3306
      - DATABASE_DIALECT=mysql
    depends_on:
      - db
    links:
      - db

  nextjs:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - graphql
    links:
      - graphql
    environment:
      API_URL: http://localhost:5000/graphql

